import { Inter } from 'next/font/google';
import '@/styles/globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'Eventmakers',
    description: 'Generated by create next app'
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${inter.className} bg-slate-100 min-h-dvh`}>
                
                {children}
            </body>
        </html>
    );
}
